org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Loom is not yet configuration-cache compatible.
org.gradle.configuration-cache=false
org.gradle.java.installations.paths=/opt/homebrew/opt/openjdk@25/libexec/openjdk.jdk/Contents/Home

# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.155.2+26.2

mod_version=0.1.0
maven_group=dev.awdllan
archives_base_name=awdl-lan
